---
kind: pipeline
type: docker
name: default

steps:
- name: install, run scripts and build doc
  image: python:3.8
  commands:
  - git fetch --tags
  - python setup.py install
  - pip install coverage sphinx sphinx-rtd-theme
  - cd tests
  - coverage run --source dectree ci_tests.py
  - coverage json
  - python coverage.py 
  - coverage report
  - cd doc
  - make html

- name: develop
  image: python:3.8
  commands:
  - python setup.py develop

- name: generate sdist
  image: python:3.8
  commands:
  - git fetch --tags
  - python setup.py sdist

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: upload_doc_master
  image: appleboy/drone-scp
  when:
    event: push
    branch: master
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/dectree/
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password

